### ISSUE TITLE
Feature Request: Enhance Pre-Curation Card with Advanced Capabilities

### ISSUE THREAD

**Issue by berntpopp** [berntpopp/gene-curator#61]
### Summary
Improve the Pre-Curation Form in the Gene Curator application by implementing features such as prefilling form fields with data from the gene card, calculating a curation score, adding a Binning system, and validating input fields to prevent overwriting of critical recommendations for lump/split decisions.

### Description
The current Pre-Curation Form can be optimized for efficiency and accuracy. The proposed enhancements include automatically filling in form fields with relevant data from the gene card, implementing a system to calculate a curation score based on user inputs, and adding validation checks to safeguard against unintentional overwriting of important lump/split recommendations.

### Acceptance Criteria
- [x] Prefill certain fields of the Pre-Curation Form based on the associated gene card data.
- [x] Develop a curation score calculation mechanism that reflects the user's inputs on the form.

- [ ] Implement input validation to prevent accidental overwriting of crucial lump/split recommendations.
- [ ] Ensure that the form remains user-friendly and intuitive, with clear guidance and feedback for the users.

### User Stories
- As a curator, I want the form to automatically fill in relevant information from the gene card to save time and reduce errors.
- As a researcher, I would appreciate a scoring system that helps in assessing the gene based on various criteria.
- As a user, I want to be alerted if I am about to overwrite important decisions to prevent data integrity issues.

### Implementation Details
- Utilize the data-binding features of Vue.js to sync data between the gene card and the Pre-Curation Form.
- Design and implement a scoring algorithm that takes into account various factors from the form inputs.
- Add validation rules that check for conflicts or potential overwrites of critical decisions, prompting the user for confirmation.

### Code Snippet
```vue
<template>
  ...
  <v-select
    v-model="precurationData.decision"
    :items="['Split', 'Lump']"
label="Decision"
hide-details

</v-select>
...
<v-textarea
v-model="precurationData.comment"
label="Comment"
auto-grow
rows="1"
no-resize
:rules="[validateDecisionOverwrite]"

</v-textarea>
...
</template>

<script>
export default {
  ...
  methods: {
    validateDecisionOverwrite(value) {
      // Custom validation logic to check for overwriting of lump/split recommendation
      if (this.isCriticalRecommendationOverwrite(value)) {
        return 'Warning: You are about to overwrite a critical recommendation!';
      }
      return true;
    },
    isCriticalRecommendationOverwrite(value) {
      // Implement logic to determine if the input value is overwriting a critical decision
      ...
    },
    ...
  },
  ...
};
</script>
```

**Comment by berntpopp** [comment]
## Status Update (2026-01-12)

**Progress**: 60% complete

### What's Done ✅
- Schema-driven form rendering (backend)
- Scoring engine integration
- `PrecurationForm.vue` created with Pinia store integration

### What's Pending ❌
- DynamicForm component wiring
- Binning system
- Advanced prefill validation

**Milestone**: Moved to v0.4.0 - Core Curation Features
**Labels**: priority: high, type: feature

This will be fully addressed alongside #62 as part of Enhancement #009.
